[admin.storage]
connection_string = "mongodb://apibara:apibara@mongo:27017"
[network.starknet-goerli]
type = "starknet"
provider_url = "https://starknet-goerli.apibara.com/" #"https://starknet-goerli.apibara.com/"