version: "3"

services:
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: apibara
      MONGO_INITDB_ROOT_PASSWORD: apibara
    ports:
      - 27017:27017

  apibara:
    image: apibara/apibara:0.3.2
    restart: always
    command: start --config /usr/etc/apibara/configuration.toml
    environment:
      RUST_LOG: "apibara=info"
    ports:
      - 7171:7171
    volumes:
      - ./configuration.toml:/usr/etc/apibara/configuration.toml
    links:
      - mongo
