version: "3"

services:
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: apibara
      MONGO_INITDB_ROOT_PASSWORD: apibara
    ports:
      - 27017:27017
    volumes:
      - /etc/starknet-id-indexer/mongo_volume:/data/db

  apibara:
    image: apibara/apibara:0.3.1
    restart: always
    command: start --config /usr/etc/apibara/configuration.toml
    environment:
      RUST_LOG: "apibara=info"
    ports:
      - 7171:7171
    volumes:
      - ./configuration.toml:/usr/etc/apibara/configuration.toml
    links:
      - mongo

  indexer:
    build: .
    command: python -u indexer
    restart: always
    ports:
      - 8082:8082
    links:
      - apibara
    volumes:
      - /etc/starknet-id-indexer/indexer_volume:/indexer/data
