version: "3"

services:

  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: apibara
      MONGO_INITDB_ROOT_PASSWORD: apibara
    ports:
      - 27017:27017
    volumes:
      - ./_docker/apibara_mongodb:/data/db

  indexer:
    container_name: indexer
    build: .
    command: python -u indexer
    restart: always
    ports:
      - 8082:8082
    volumes:
      - ./_docker/starknet-id-indexer:/indexer/data
    links:
      - mongo

  nginx:
    image: valian/docker-nginx-auto-ssl
    restart: on-failure
    ports:
      - 80:80
      - 443:443
    volumes:
      - ssl_data:/etc/resty-auto-ssl
    environment:
      ALLOWED_DOMAINS: 'goerli.indexer.starknet.id'
      SITES: 'goerli.indexer.starknet.id=indexer:8082'

volumes:
  ssl_data:
