version: "3"

services:

  indexer:
    container_name: indexer
    build: .
    command: python -u indexer
    restart: always
    ports:
      - 8082:8082
    volumes:
      - ./_docker/starknet-id-indexer:/indexer/data

  nginx:
    image: valian/docker-nginx-auto-ssl
    restart: on-failure
    ports:
      - 80:80
      - 443:443
    volumes:
      - ssl_data:/etc/resty-auto-ssl
    environment:
      ALLOWED_DOMAINS: 'indexer.starknet.id'
      SITES: 'indexer.starknet.id=indexer:8082'

volumes:
  ssl_data:
