version: '3'

services:

  indexer:
    container_name: indexer
    build: .
    command: python -u indexer
    restart: always
    ports:
      - 8082:8082
    volumes:
      - ./_docker/starknet-id-indexer:/indexer/data